### ISSUE TITLE
shoreline constraints 

### ISSUE THREAD

**Issue by huyquangtranaus** [CHLNDDEV/OceanMesh2D#110]
![mesh_](https://user-images.githubusercontent.com/32722297/91219121-7c345280-e75d-11ea-8565-09bd468b5d77.png)
Hi Keith, William,

I am making a mesh over the wharf like the land, but I want to keep its shape (e.g. straight line, not weirs)  An example is attached.  Is OceanMesh2D capable of doing that?

Thanks, mates 
Huy

**Comment by krober10nd** [comment]
Hey Huy, 


Yes, we have an example that shows how to do something like that here...
https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/Examples/Example_6b_GBAY_w_floodplain.m

We first mesh to the datum in a water tight fashion, then we use `extractFixedConstraints` to get the vertices and edges along the mainland and island boundaries so that these points and edges will be constrained in the subsequent meshing step. 

Then we define a new `geodata` using a contour of a higher height (e.g., 10-m) and call the mesh generator with the `pfix` and `egfix`. Note in this second call to `meshgen` we re-use the same sizing function. All sizing options can be specified by depth-ranges, which is shown in the example.

**Comment by huyquangtranaus** [comment]
![GBBAY](https://user-images.githubusercontent.com/32722297/91225365-dbe32b80-e766-11ea-8887-fa635b5315c3.png)
Cool, Keith,

Yes, I  explored that example before. I see it could be one solution for me. However,  when I zoom in, I don't see we have a straight (extract, sharp) line as a screenshot attached? In that case, I anticipate that there might be some bad elements along the line, but can we do that?

**Comment by krober10nd** [comment]
I would suggest to plot the mesh `plot(m,'bmesh',0)` and then plot the edge constraints `hold on; drawedge2(pfix,egfix)` and then zoom in to make sure. 

All edge constraints should be retained and your `mshgen.build` should have a different looking output showing the edge constraining algorithm is active.

**Comment by huyquangtranaus** [comment]
![1](https://user-images.githubusercontent.com/32722297/91227650-3336cb00-e76a-11ea-82d2-09a3fce8dc4e.png)
Oh yes, I see somewhere in the mesh (attached), can we also make two parallel straight lines along a shipping channel? That would be a powerful feature then.

**Comment by krober10nd** [comment]
glad it's working, the translation in location is likely due to the projection you built the mesh in but that's just a guess. 

And yes, that's already all in there. what you could is this:

1. Build a sizing function 
2. Draw a line along your channel and increase point spacing to `h0` using the function `my_interpm`
3. Apply the decimation technique that we use for the initial point rejection to remove some points from the line. This is so the point spacing along the line agrees with the sizing function.
4. Pass these points and edges to `mshgen`

**Comment by krober10nd** [comment]
I could make a simple function to do the above but maybe you could first take a stab at it.

**Comment by krober10nd** [comment]
@huyquangt  can you post your code so I can see what's going on to create these images?

**Comment by huyquangtranaus** [comment]
hello @krober10nd, I used the example Example_6b_GBAY_w_floodplain.m to make these images.

**Comment by krober10nd** [comment]
Ah ok then I would turn off cleanup in mshgen. And then do it after with the implicit smoother turned off. That can shift points unfortunately.

**Comment by huyquangtranaus** [comment]
do you have time to do it soon? then I can have a try 

Thanks mate

**Comment by huymetocean** [comment]
Hey Keith @krober10nd  it seems to me that in the example /Example_6b_GBAY_w_floodplain.m, the constraints are applied to the entire (outer) edges for mapping the main land. Can we only apply part of it?

**Comment by krober10nd** [comment]
I ran the `Example_6b_GBAY_w_floodplain.m` to completion and I only see the shoreline and islands being constrained (blue edges).
<img width="1440" alt="Screen Shot 2020-08-26 at 12 34 37 PM" src="https://user-images.githubusercontent.com/18619644/91324534-92abcf80-e798-11ea-9e4d-70dc4b0f9e0c.png">

But yes, if you run meshgen with `cleanup, 1` then this destroys both pfix and egfix because of the option `ds`. Something to look more into but the solution is to defer cleaning to after mesh generation is completed and run it with a custom option set that doesn't do `direct_smooth` (e.g., `ds,0`)

I don't think I have time to look into the channel constraints thing at least for the next few weeks.

**Comment by krober10nd** [comment]
<img width="1440" alt="Screen Shot 2020-08-26 at 1 23 56 PM" src="https://user-images.githubusercontent.com/18619644/91330138-6cd5f900-e79f-11ea-91f7-b8189e7302f7.png">

**Comment by CHLNDDEV** [comment]
#264
