### ISSUE TITLE
Smooth(er) outer buffer?

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#111]
https://github.com/CHLNDDEV/OceanMesh2D/blob/f0d0f6ebcd0ac4f2504320c9d3a82e9ce453521d/%40meshgen/private/smooth_outer.m#L10

~~Increasing the multiplier on `dx` and `dy` makes resolution transitions smoother between nests appeasing some our our more critical users.~~

**Comment by krober10nd** [comment]
My opinion on this is that we should only enforce a smooth gradation between the transition zones *between* nests, not grade the whole nest (since that was already done).

**Comment by krober10nd** [comment]
If we only smooth the transition zone, we could use a smoother grade and thus increase the quality of the meshes.

**Comment by WPringle** [comment]
My thinking in the design of this was that it seemed really neat & tidy to just resmooth the outer after interpolating the inner inside of it (based on whatever you set the grade of the outer to be). That way you don't even need to define a transition zone, and since most of the outer is already smooth it shouldn't take that long to converge. Therefore, "fast" transitions only arise if the gradation of the outer nest is itself a high value, which the user already seemingly is happy to accept. 

The part you are pointing to is not the definition of the "transition zone" or anything like that. That is only used to do a quick search to determine if there are any "inner" points inside the "outer".

**Comment by WPringle** [comment]
Nevertheless, I am open to a redesign of smooth_outer that instead of re-smoothing the outer with its gradation rate, we smooth a transition zone based on the grade of the inner (or the minimum of inner or outer grade).  I think we should get Coleman's @cblakely97 script that he made to do the "smooth_inner" thing and compare.

**Comment by krober10nd** [comment]
Yea I agree best not to change it. We'll have another look at this on pyOM down the road

**Comment by krober10nd** [comment]
I didn't see your last message on the app. I'll leave it open in case he wants to provide some feedback. I guess smoother_inner does the opposite of smooth outer? 

I was thinking about using some kind of 2D hyperbolic tangent function to blend the two sizing functions together somehow and by pass the use of the gradation tool.

**Comment by WPringle** [comment]
Could do, but I just originally liked the idea of using the gradation rates passed by the user (as I said the implementation I came up with seemed neat and tidy conceptually).
