### ISSUE TITLE
increase `sc_maxit`

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#140]
* only one delete singly connected step by default does little in the way of removing the useless connectivity. This should be IMO be set to a large number by default (20-50) so it properly deals with the problem.

**Comment by WPringle** [comment]
So yeah originally I was thinking it should just be "inf" which get's rid of all of them. Could do that, but because it is singly connected doesn't make it useless necessarily. So the argument from my perspective is that the element at the end of the single-connected channel is usually "bad" but the ones in between are not. In some cases you might want to keep those single connected channels ay? Not sure.
