### ISSUE TITLE
Issues while interpolating bathymetry 

### ISSUE THREAD

**Issue by cnske** [CHLNDDEV/OceanMesh2D#147]
Hi, 

Currently I am working on a mesh for a large lake using your amazing and straight forward tool. So far meshing works fine, but the interpolation of the bathymetry gives me some headaches. 
My bathymetric measurements are based on topographic heights of a national height system, so all values are larger than 100. Furthermore the actual raster I use for the bathymetry covers a much larger area than the actual model area. 

While interpolating I facing the following problems. 
1) Values get inverted to negative values after running OceanMesh2D
2) The interpolation creates false results, which are far off compared to the input raster
3) Generally, the whole interpolation results seems rather poor. 

My questions are. 
Is there an option to "map" my raster to the mesh without changing the values to negative ones?
Can I somehow assign my coastline to a specific elevation, which is then used a base for further interpolation combined with my input raster?
How sensitive is the interpolation to difference in the mesh resolution and the raster resolution?

Thanks for help.

**Comment by krober10nd** [comment]
Hey @cklante 

Thanks for the question. If you could provide the code snippet that you use to do the interpolation, that'd be very helpful for us.

For your specific questions:

1. This just happens because the majority of users use ADCIRC which has this inversion. Just multiply by -1  
```m.b = m.b * -1```
 at the end

2. This question requires another question on my part: Is your mesh bounded/water tight with the coastline or does it go further overland? If not, then you can extract the boundary nodes and assign an elevation after the other nodes are interpolated.

3. By default, `msh.interp` uses cell-averaging which considers the disparity in horizontal resolution between DEM and mesh and tries to use a stencil of points to smooth this out. There are ways to alter the default cell-averaging stencil size or change the interpolation type. But this leads me back to my first query asking for how you're calling/using the method in the first place.

**Comment by krober10nd** [comment]
and if you could attach a picture visualizing the problem, that'd also be very useful.

**Comment by cnske** [comment]
Hej @krober10nd,
thanks for the answer. 

I call the method as follows. 
`dem = ('Bathymetry.nc');` for importing the .nc bathymetry file.
`m = interp(m, gdat)` for interpolation. 

To get the positive value I would now just need to write `m = m * -1` as I understood you correctly.

My mesh goes much further over land. This is because the lake I model is rather large and has minor changes along the coastline elevation. Here a picture of the situation. 

A cutout of the raster file used for interpolation. The shore of the lake is aprx. at 141.38 m.
![image](https://user-images.githubusercontent.com/73825822/100609053-aaea3800-330d-11eb-8b62-c3d85aec2b0c.png)

A cutout of the mesh how it is created by OceanMesh2D
![image](https://user-images.githubusercontent.com/73825822/100608295-75911a80-330c-11eb-9513-9991eddd1ace.png)

A cutout of the bathymetry how it is interpolated by OceanMesh2D
![image](https://user-images.githubusercontent.com/73825822/100608410-a2ddc880-330c-11eb-875d-a0c3212dbac6.png)

Might be hard to see in from the pictures, but especially in the north-eastern part the differences are major.

**Comment by krober10nd** [comment]
I see and what do the triangles look like?

 This is an interesting use case. I haven't had much experience meshing lakes. One thing you should be weary of, is that 

````
m = interp(m, gdat)
````
may downsample your DEM to fit in memory depending on its size and your specified 'h0'. 

```
gdat = geodata('dem','file.nc','h0',horizo_resolution_of_dem_in_meters,'bbox',bbox);
m = interp(m,gdat,'depth');
```

If the triangles aren't water-tight with respect to the shoreline boundary of the lake, this interpolation will be naturally difficult to do since you're meshing it all at once.

**Comment by krober10nd** [comment]
ah I see you've updated the images.

**Comment by cnske** [comment]
Yeah accidentally hit the comment button to early.

**Comment by krober10nd** [comment]
I would recommend to reduce the mesh gradation rate when constructing the mesh.

**Comment by cnske** [comment]
Thank. 
If I understand you correctly I should decrease the grow rate of my mesh, which is currently set to 

`min_res = 20; 
max_res = 2000;
max_res_ns = 200; 
grade = 0.35;
R = 3; `

The min_res is that high, since the lake has a constriction smaller than 100 m and I would like to have at least 5 nodes there to make sure the simulation gives sufficient results. The bathymetry is rather steady at this area.

Reducing the mesh gradation rate, would increase the mesh resolution, resulting in long calculation times. 

Regarding the downsampling. My raster is 50x50 and h0 is 20, so I assume the up-sampling might result in issues as well? Would you recommend to up-sample the reaster in GIS first? 

Just tried it with h0 set to 50 and will check the results.

**Comment by krober10nd** [comment]
Yes, reducing the mesh gradation rate would increase calculation times but would improve the bathymetric interpolation and maybe the numerics depending on how you're solving the equations. I would think a gradation rate of 0.25 would be reasonable in this case. 

If you need at least 5 nodes across a channel set `R=5`. 

Does any message appear that it's downsampling the DEM when you load it in to the `geodata`class?

**Comment by WPringle** [comment]
Can also just try `m = interp(m,dem)` without converting to gdat

**Comment by krober10nd** [comment]
Also, @cklante you can ask questions on the slack channel which we're trying to get more movement on.

**Comment by krober10nd** [comment]
A case was presented by the author of this thread that produces incorrect cell-averaging. We are investigating further as time permits.
