### ISSUE TITLE
more intuitive deactivation of `msh.clean()` options

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#180]
* If one wants to turn off the nodal valency reducer, one has to pass a kwarg argument of <= 5 to `msh.clean()`

```
m = clean(m,'con',5);
```

which is a bit not obvious. ~~Perhaps this should be 0 to deactivate or your write the word "off"?~~

The reason I bring this up is if you want to transfer nodal attributes between a non-clean and clean mesh, the valency reducer will get in the way and the prompt will say that "if you run with nodal valency reducer, all nodal attributes will be lost".

Perhaps in this prompt, we should suggest how to turn it off as well.

**Comment by WPringle** [comment]
First thing to say is that you can use 0 and I always use that.

But I agree that prompt is incredibly annoying. Here are my suggested changes:

1. Change 'passive' option to turn this con to 0 by default. 
2. Instead of the prompt we should just put in a warning, and then try to map all the attributes over using nearest neighbor (map_mesh_properties should be able to handle this) even though it won't be perfect since new nodes are added etc.
