### ISSUE TITLE
Help required in meshing above the geoid #help #meshing

### ISSUE THREAD

**Issue by 123jk26** [CHLNDDEV/OceanMesh2D#218]
Is it possible to mesh up to +10m contours above the geoid, for the study purpose about coastal inundation
if possible, where can I give the input?  I mean, in which class?

**Comment by krober10nd** [comment]
Hey @123jk26 I would take a look at this example https://github.com/CHLNDDEV/OceanMesh2D/blob/Projection/Examples/Example_6b_GBAY_w_floodplain.m

The boundary of the meshing domain just has to be a polygon but it can represent any geoid elevation. In order to accomplish what you're wanting to do, you would build a mesh sizing function (e.g., an `edgefx`) using geospatial data  (contained in a `geodata` class) from a shoreline (e.g., 0-m or something similar). Then you'd create another `geodata` class with your +10 m contour for example and this would be the meshing boundary you'd pass to `meshgen`.

In this way, the meshing domain would extend up to +10-m but the mesh sizing variations would follow the shoreline you passed.

**Comment by 123jk26** [comment]
I've created a mesh accordingly and ran the output Fort.14 file in adcirc. All the time I am getting the elevation error(water surface elevation crosses 20m above datum), which (according to the ADCIRC manual) is due to the unstable mesh. how can I ensure the stability of the mesh? which are the user inputs that will affect the stability of generated mesh, mainly?

**Comment by krober10nd** [comment]
Like your other issue, I need to see what you’re doing. So code, inputs and figures. Is this your first time running ADCIRC? 

Are you familiar with numerical simulation concepts in general?
