### ISSUE TITLE
user guide corrections for Calc_IT_Fric() and write() usage

### ISSUE THREAD

**Issue by HamishB** [CHLNDDEV/OceanMesh2D#28]
Hi,

In the pdf user guide's Typical Workflow Example (sec. 6.9), line 30 of the listing says:
``` 
m = Calc_IT_Fric(m,'Nfname',BUOYFILE) ;
```

but the current version of the function does not have 'Nfname' as a varargin pair, it's mandatory. So if you try to run the code as presented it looks for a file called 'Nfname.mat', unsuccessfully.

Also TPXO is now up to version 10, you may want to update that link in the text of the section.

(by the way, the final version of WOA 2018 is now available for download since Aug 29th, I don't think it is announced anywhere but the netCDF internal metadata will show it)

---

In the 7.1.2 Methods help for write() it says:
```
however, the user can optionally decide
to write only a select few of these files by passing a comma-delimited list of the post-fix name
types (e.g., 14,15 to denote fort.14 or fort.15).
```

it looks for a string not an int, so: `e.g '14','15' to denote fort.14 or fort.15` helps the reader avoid a few moments of confusion.

thanks,
Hamish

**Comment by krober10nd** [comment]
Thanks Hamish, I took care of those on the Overleaf user guide.

**Comment by WPringle** [comment]
Hi Hamish,
Thanks for going through everything to fix up the inconsistencies!
I don't see TPXO version 10 though. The [version 9](http://volkov.oce.orst.edu/tides/tpxo9_atlas.html) of the TPXO atlas appears relatively recent. In the dev branch last week or so I added the [capability to use the TPXO9-atlas](https://github.com/CHLNDDEV/OceanMesh2D/commit/2a13a6ab1da549562f24ead137a397a4d104e339) which instead of one file for TPXO9.1 it is many individual files for each constituent. The TPXO9-atlas should be better than TPXO9.1 in general.

**Comment by HamishB** [comment]
Sorry nevermind about the TPXO10, I was getting it mixed up with TEOS-10.
