### ISSUE TITLE
Mesh Corner Elements coordinate error

### ISSUE THREAD

**Issue by DrakonianMight** [CHLNDDEV/OceanMesh2D#29]
Hi, 

Apologies for raising another issue, so far I have been pretty impressed with the adaptability, I have read through the manual and cannot seem to find anything that I think might help other than perhaps using pfix in meshgen at the corners. 

So I started by using example_2_NY as a starting point and have been progressively worked from there add elements I want. However all the nested meshes I produce either one or both of the eastern boundaries seem to end up with some sort of error, whereby the coordinates for those elements seem to be 0,0.
![image](https://user-images.githubusercontent.com/46990198/64656359-8852d180-d472-11e9-9129-3489be567890.png)

Attached is my matlab file:
[mesh_build_gc_nest.txt](https://github.com/CHLNDDEV/OceanMesh2D/files/3598078/mesh_build_gc_nest.txt)

The reason I think that it is a coordinate error is when I import the file to Blue Kenue it looks like the below.

![image](https://user-images.githubusercontent.com/46990198/64656490-f8615780-d472-11e9-86b8-508bf985db07.png)

Thanks, 

Drak

**Comment by WPringle** [comment]
Hi Drak,

I'm not sure what you mean by coordinate error and why the triangles should look like that in Blue Kenue... 

I ran your script with the gshhs shoreline and the [grb bathymetry](https://www.deepreef.org/bathymetry/65-3dgbr-bathy.html) and the coordinates were fine.

What I'm seeing here is actually a problem with the interpolation of the bathymetry. When you use the gdat to interpolate sometimes it can miss the corners because the point is just outside of the extracted bathy data. A simple way to avoid this is to use the 'nan','fill' option, i.e., 
m = interp(m,gdat,'nan','fill');

or you can just interpolate directly from the dem:
dem = 'gbr100_16jan.nc';
m = interp(m,dem);

When the dem is used to interpolate it will extract the region of interest from the dem with a buffer region so it will not have issues at the corners.

![image](https://user-images.githubusercontent.com/21131934/64657872-e512a580-d3fa-11e9-9eb0-62d75bc47e4f.png)

I noticed an issue with using the grb bathymetry to interpolate directly due to the y-coordinates being in the upside down direction - I will need to make sure it works for this case too.

**Comment by DrakonianMight** [comment]
Thanks for getting back to me so fast!

Yes interpolating directly from the DEM solved the issue.

FYI, with Blue Kenue it appears that when it ingests the .14 format it doesn't pull in the coordinates properly if the elevation isn't there/ is not what it's expecting.

Great job with the module though, it is taking me a fraction of the time to make some nice mesh's.

**Comment by WPringle** [comment]
Yeah that's interesting about Blue Kenue, I figured something like that but the default bathymetry is usually just zero so I didn't think that a bathymetry value of zero would cause such a strange visualization. 

Anyway, great to hear it worked and looking forward to seeing more meshes.
